# Generated by Django 2.0.4 on 2018-04-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(unique=True)),
                ('reading_range_high', models.IntegerField(unique=True)),
                ('reading_range_low', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(unique=True)),
                ('choice1', models.TextField(unique=True)),
                ('choice2', models.TextField(unique=True)),
                ('choice3', models.TextField(unique=True)),
                ('choice4', models.TextField(unique=True)),
                ('correct', models.IntegerField()),
                ('feedback', models.TextField(blank=True, unique=True)),
                ('date', models.DateField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Level')),
            ],
        ),
        migrations.CreateModel(
            name='LevelWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Level')),
            ],
        ),
    ]
