# Generated by Django 2.0.4 on 2018-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180426_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelquestion',
            name='choice1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice4',
            field=models.TextField(),
        ),
    ]
