# Generated by Django 2.0.4 on 2018-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_levelquestion_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelquestion',
            name='question_genre',
            field=models.IntegerField(choices=[('', '---------'), (1, 'politics'), (9, 'tech'), (10, 'lifestyle'), (2, 'sports'), (3, 'science'), (4, 'entertainment'), (5, 'world'), (6, 'nation'), (7, 'environment'), (8, 'business and commerce'), (11, 'others')], default=1),
            preserve_default=False,
        ),
    ]
