# Generated by Django 2.0.5 on 2018-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20180515_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelquestion',
            name='concept',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='feedback',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='sub_concept',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='vocab_word',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
