# Generated by Django 2.0.5 on 2018-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20180515_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelquestion',
            name='question_inst',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='question_text',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='levelwords',
            name='word',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
