# Generated by Django 2.0.5 on 2018-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20180515_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelquestion',
            name='que_format',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
