# Generated by Django 2.0.5 on 2018-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20180515_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelquestion',
            old_name='vocab_word',
            new_name='question_word',
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='choice4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='option_create',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='levelquestion',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
