# Generated by Django 2.0.5 on 2018-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_offwords_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offwords',
            name='category',
            field=models.CharField(default='new', max_length=25),
            preserve_default=False,
        ),
    ]
