# Generated by Django 2.0.5 on 2018-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_offwords_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelquestion',
            name='difficulty',
            field=models.IntegerField(choices=[('', '---------'), (1, 'low'), (2, 'medium'), (3, 'high')]),
        ),
    ]
